version: '3.7'

services:
  redis:
    image: redis/redis-stack
    restart: always
    container_name: modelate_redis
    command: redis-server --requirepass a3192f4d42bd
    volumes:
      - $HOME/modelate-redis:/data
    ports:
      - '6369:6379'

  database:
      image: mysql:8.0.31-debian
      restart: always
      container_name: modelate_mysql
      env_file:
        - .env
      ports:
        - '3310:3306'
      volumes:
        - $HOME/modelate-mysql:/var/lib/mysql

  flaskapp:
      build: ./modelate
      restart: always
      command: flask run
      container_name: modelate_app
      volumes:
        - .:/code
      env_file:
        - .env
      ports:
        - '5000:5000'
      depends_on:
        - database