version: '3.7'

services:
  redis:
    image: 'redis:5.0.6'
    restart: always
    container_name: modelate_redis
    command: redis-server --requirepass a3192f4d42bd
    volumes:
      - $HOME/modelate-redis:/data
    ports:
      - '6369:6379'

  database:
    image: postgres:12.0-alpine
    restart: always
    container_name: modelate_psql
    environment:
      POSTGRES_DB: 'modelate'
      POSTGRES_USER: 'backend'
      POSTGRES_PASSWORD: 'd3c885805581'
    ports:
      - '5442:5432'
    volumes:
      - $HOME/modelate-psql:/var/lib/postgresql/data

  flaskapp:
      build: ./modelate
      restart: always
      command: flask run
      container_name: modelate_app
      volumes:
        - .:/code
      environment:
        FLASK_SKIP_DOTENV: 0
        FLASK_APP: wsgi.py
        FLASK_DEBUG: 1
        FLASK_RUN_HOST: 0.0.0.0

        SITE_NAME: modelate
        SECRET_KEY: 5d5a4c4b57ac80297ec16c712fb17784557e
        MODELATE_STATUS: modelate.config.DevelopmentConfig

        REDIS_PASSWORD: a3192f4d42bd
        REDIS_HOST: redis
        REDIS_PORT: 6379
        REDIS_DB_NO: 0

        DB_TYPE: POSTGRES

        POSTGRES_HOST: database
        POSTGRES_PORT: 5432
        POSTGRES_USERNAME: backend
        POSTGRES_PASSWORD: d3c885805581
        POSTGRES_DB: modelate
      ports:
        - '5000:5000'
      depends_on:
        - database